# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 10:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('t', 'Tirada'), ('c', 'Campeonato')], default='c', max_length=1)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrellas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('jugadores', models.ManyToManyField(related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('numero', models.IntegerField(default=0)),
                ('jugadores', models.ManyToManyField(related_name='rondas', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='juego.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='Tirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('posicion_ronda', models.IntegerField(default=0)),
                ('acierto', models.NullBooleanField(default=None)),
                ('fallo', models.NullBooleanField(default=None)),
                ('tipo', models.CharField(choices=[('norm', 'Normal'), ('espe', 'Especial'), ('estr', 'Estrella')], default='norm', max_length=4)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiradas', to=settings.AUTH_USER_MODEL)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='juego.Ronda')),
            ],
        ),
        migrations.AddField(
            model_name='estrella',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrellas', to='juego.Partida'),
        ),
    ]
