# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='estado',
            field=models.CharField(choices=[('ini', 'Iniciada'), ('fin', 'Finalizada'), ('sus', 'Suspendida')], default='ini', max_length=3),
        ),
        migrations.AddField(
            model_name='ronda',
            name='max_aciertos',
            field=models.IntegerField(default=0),
        ),
    ]
